coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%
  ignore:
    - "tests/.*"
    - "examples/.*"
    - "src/metatrain/experimental/.*"
    - "src/metatrain/utils/distributed/.*"

comment: false
